export default [
  {english: 'abide by',
  translation: 'zich houden aan'},
  {english: 'accrued',
  translation: 'opgebouwd'},
  {english: 'adage',
  translation: 'gezegde'},
  {english: 'advent',
  translation: 'komst'},
  {english: 'adversary',
  translation: 'tegenstander'},
  {english: 'ailing',
  translation: 'noodlijdend'},
  {english: 'alluded',
  translation: 'gezinspeeld'},
  {english: 'arduous',
  translation: 'zwaar'},
  {english: 'attainability',
  translation: 'haalbaarheid'},
  {english: 'bargain',
  translation: 'overeenkomst'},
  {english: 'begrudgingly',
  translation: 'met tegenzin'},
  {english: 'candidly',
  translation: 'openhartig'},
  {english: 'carpenter',
  translation: 'timmerman'},
  {english: 'comprise',
  translation: 'omvatten'},
  {english: 'conscientious',
  translation: 'gewetensvol'},
  {english: 'contend',
  translation: 'beweren'},
  {english: 'convoluted',
  translation: 'ingewikkeld'},
  {english: 'crave',
  translation: 'snakken naar'},
  {english: 'cringe',
  translation: 'ineenkrimpen'},
  {english: 'curfew',
  translation: 'avondklok'},
  {english: 'deliberately',
  translation: 'opzettelijk'},
  {english: 'dire',
  translation: 'verschrikkelijk'},
  {english: 'disdain',
  translation: 'minachting'},
  {english: 'dismal',
  translation: 'somber'},
  {english: 'dissuade',
  translation: 'afraden'},
  {english: 'divisive',
  translation: 'verdeeldheid zaaien'},
  {english: 'drain',
  translation: 'uitputten'},
  {english: 'dreaded',
  translation: 'gevreesde'},
]